services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    image: germancruzpallares/back-vueapp:latest
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=appdb;User=sa;Password=Your_password123;TrustServerCertificate=True
    depends_on:
      - db

  frontend:
    image: germancruzpallares/front-vueapp:latest
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mssql_data:
